# Generated by precisionFDA exporter (v1.0.3) on 2018-06-14 03:38:45 +0000
# The asset download links in this file are valid only for 24h.

# Exported app: primus, revision: 6, authored by: jeffrey.staples.2
# https://precision.fda.gov/apps/app-F096G0Q08vKjB80B4kPK1j8f

# For more information please consult the app export section in the precisionFDA docs

# Start with Ubuntu 14.04 base image
FROM ubuntu:14.04

# Install default precisionFDA Ubuntu packages
RUN DEBIAN_FRONTEND=noninteractive apt-get update && apt-get install -y \
	aria2 \
	byobu \
	cmake \
	cpanminus \
	curl \
	dstat \
	g++ \
	git \
	htop \
	libboost-all-dev \
	libcurl4-openssl-dev \
	libncurses5-dev \
	make \
	perl \
	pypy \
	python-dev \
	python-pip \
	r-base \
	ruby1.9.3 \
	wget \
	xz-utils

# Install default precisionFDA python packages
RUN pip install \
	requests==2.5.0 \
	futures==2.2.0 \
	setuptools==10.2

# Add DNAnexus repo to apt-get
RUN /bin/bash -c "echo 'deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/amd64/' > /etc/apt/sources.list.d/dnanexus.list"
RUN /bin/bash -c "echo 'deb http://dnanexus-apt-prod.s3.amazonaws.com/ubuntu trusty/all/' >> /etc/apt/sources.list.d/dnanexus.list"
RUN curl https://wiki.dnanexus.com/images/files/ubuntu-signing-key.gpg | apt-key add -

# Update apt-get
RUN DEBIAN_FRONTEND=noninteractive apt-get update

# Download app assets
RUN curl https://dl.dnanex.us/F/D/vYPgQ2QpFzxJp29Q7Qz8bXVv7JgzvxJ8889g0F68/PRIMUSv1.9.0_mac.tar.gz | tar xzf - -C / --no-same-owner --no-same-permissions

# Download helper executables
RUN curl https://dl.dnanex.us/F/D/0K8P4zZvjq9vQ6qV0b6QqY1z2zvfZ0QKQP4gjBXp/emit-1.0.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions
RUN curl https://dl.dnanex.us/F/D/bByKQvv1F7BFP3xXPgYXZPZjkXj9V684VPz8gb7p/run-1.2.tar.gz | tar xzf - -C /usr/bin/ --no-same-owner --no-same-permissions

# Write app spec and code to root folder
RUN ["/bin/bash","-c","echo -E \\{\\\"spec\\\":\\{\\\"input_spec\\\":\\[\\{\\\"name\\\":\\\"plink_genome_file\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"plink_genome_file\\\",\\\"help\\\":\\\".genome\\ file\\ generated\\ by\\ PLINK\\\"\\},\\{\\\"name\\\":\\\"degree_rel\\\",\\\"class\\\":\\\"int\\\",\\\"optional\\\":true,\\\"label\\\":\\\"Maximum\\ degree\\ of\\ relatedness\\ used\\ in\\ reconstruction\\\",\\\"help\\\":\\\"\\\",\\\"default\\\":1,\\\"choices\\\":\\[1,2,3\\]\\}\\],\\\"output_spec\\\":\\[\\{\\\"name\\\":\\\"primus_results\\\",\\\"class\\\":\\\"file\\\",\\\"optional\\\":false,\\\"label\\\":\\\"PRIMUS\\ results\\ in\\ a\\ tar\\ ball\\\",\\\"help\\\":\\\"\\\"\\}\\],\\\"internet_access\\\":false,\\\"instance_type\\\":\\\"baseline-2\\\"\\},\\\"assets\\\":\\[\\\"file-F095g600jP4Xg2Q4k5K0jvxQ\\\"\\],\\\"packages\\\":\\[\\]\\} \u003e /spec.json"]
RUN ["/bin/bash","-c","echo -E \\{\\\"code\\\":\\\"cd\\ /PRIMUS_v1.9.0/bin/\\\\n\\\\n./run_PRIMUS.pl\\ -p\\ \\\\\\\"\\$plink_genome_file_path\\\\\\\"\\ --degree_rel\\ \\$degree_rel\\ --out\\ \\\\\\\"\\$plink_genome_file_name\\\\\\\"_PRIMUS\\\\n\\\\ntar\\ -cf\\ \\\\\\\"\\$plink_genome_file_name\\\\\\\"_results.tar\\ \\\\\\\"\\$plink_genome_file_name\\\\\\\"_PRIMUS\\\\n\\\\nemit\\ primus_results\\ \\\\\\\"\\$plink_genome_file_name\\\\\\\"_results.tar\\\\n\\\"\\} | python -c 'import sys,json; print json.load(sys.stdin)[\"code\"]' \u003e /script.sh"]

# Create directory /work and set it to $HOME and CWD
RUN mkdir -p /work
ENV HOME="/work"
WORKDIR /work

# Set entry point to container
ENTRYPOINT ["/usr/bin/run"]

VOLUME /data
VOLUME /work